/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as NusqaIndexRouteImport } from './routes/nusqa/index'
import { Route as HomeworkIndexRouteImport } from './routes/homework/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TestsTestIdRouteImport } from './routes/tests/$testId'
import { Route as TeacherReportsRouteImport } from './routes/teacher/reports'
import { Route as TeacherLessonsRouteImport } from './routes/teacher/lessons'
import { Route as TeacherHomeworkRouteImport } from './routes/teacher/homework'
import { Route as SubjectsSubjectSlugRouteImport } from './routes/subjects/$subjectSlug'
import { Route as HomeworkHwIdRouteImport } from './routes/homework/$hwId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminScheduleRouteImport } from './routes/admin/schedule'
import { Route as TestsTestIdResultRouteImport } from './routes/tests/$testId.result'
import { Route as SubjectsSubjectSlugLessonLessonIdRouteImport } from './routes/subjects/$subjectSlug.lesson.$lessonId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const NusqaIndexRoute = NusqaIndexRouteImport.update({
  id: '/nusqa/',
  path: '/nusqa/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkIndexRoute = HomeworkIndexRouteImport.update({
  id: '/homework/',
  path: '/homework/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdRoute = TestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/teacher/reports',
  path: '/teacher/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLessonsRoute = TeacherLessonsRouteImport.update({
  id: '/teacher/lessons',
  path: '/teacher/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherHomeworkRoute = TeacherHomeworkRouteImport.update({
  id: '/teacher/homework',
  path: '/teacher/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectSlugRoute = SubjectsSubjectSlugRouteImport.update({
  id: '/subjects/$subjectSlug',
  path: '/subjects/$subjectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkHwIdRoute = HomeworkHwIdRouteImport.update({
  id: '/homework/$hwId',
  path: '/homework/$hwId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/admin/schedule',
  path: '/admin/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdResultRoute = TestsTestIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => TestsTestIdRoute,
} as any)
const SubjectsSubjectSlugLessonLessonIdRoute =
  SubjectsSubjectSlugLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => SubjectsSubjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/homework/$hwId': typeof HomeworkHwIdRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRouteWithChildren
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/lessons': typeof TeacherLessonsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/tests/$testId': typeof TestsTestIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/homework/': typeof HomeworkIndexRoute
  '/nusqa/': typeof NusqaIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/tests/$testId/result': typeof TestsTestIdResultRoute
  '/subjects/$subjectSlug/lesson/$lessonId': typeof SubjectsSubjectSlugLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/homework/$hwId': typeof HomeworkHwIdRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRouteWithChildren
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/lessons': typeof TeacherLessonsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/tests/$testId': typeof TestsTestIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/homework': typeof HomeworkIndexRoute
  '/nusqa': typeof NusqaIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/tests': typeof TestsIndexRoute
  '/tests/$testId/result': typeof TestsTestIdResultRoute
  '/subjects/$subjectSlug/lesson/$lessonId': typeof SubjectsSubjectSlugLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/homework/$hwId': typeof HomeworkHwIdRoute
  '/subjects/$subjectSlug': typeof SubjectsSubjectSlugRouteWithChildren
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/lessons': typeof TeacherLessonsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/tests/$testId': typeof TestsTestIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/homework/': typeof HomeworkIndexRoute
  '/nusqa/': typeof NusqaIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/tests/$testId/result': typeof TestsTestIdResultRoute
  '/subjects/$subjectSlug/lesson/$lessonId': typeof SubjectsSubjectSlugLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/admin/schedule'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/homework/$hwId'
    | '/subjects/$subjectSlug'
    | '/teacher/homework'
    | '/teacher/lessons'
    | '/teacher/reports'
    | '/tests/$testId'
    | '/admin/'
    | '/homework/'
    | '/nusqa/'
    | '/subjects/'
    | '/teacher/'
    | '/tests/'
    | '/tests/$testId/result'
    | '/subjects/$subjectSlug/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/admin/schedule'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/homework/$hwId'
    | '/subjects/$subjectSlug'
    | '/teacher/homework'
    | '/teacher/lessons'
    | '/teacher/reports'
    | '/tests/$testId'
    | '/admin'
    | '/homework'
    | '/nusqa'
    | '/subjects'
    | '/teacher'
    | '/tests'
    | '/tests/$testId/result'
    | '/subjects/$subjectSlug/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/admin/schedule'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/homework/$hwId'
    | '/subjects/$subjectSlug'
    | '/teacher/homework'
    | '/teacher/lessons'
    | '/teacher/reports'
    | '/tests/$testId'
    | '/admin/'
    | '/homework/'
    | '/nusqa/'
    | '/subjects/'
    | '/teacher/'
    | '/tests/'
    | '/tests/$testId/result'
    | '/subjects/$subjectSlug/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  HomeworkHwIdRoute: typeof HomeworkHwIdRoute
  SubjectsSubjectSlugRoute: typeof SubjectsSubjectSlugRouteWithChildren
  TeacherHomeworkRoute: typeof TeacherHomeworkRoute
  TeacherLessonsRoute: typeof TeacherLessonsRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TestsTestIdRoute: typeof TestsTestIdRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  HomeworkIndexRoute: typeof HomeworkIndexRoute
  NusqaIndexRoute: typeof NusqaIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nusqa/': {
      id: '/nusqa/'
      path: '/nusqa'
      fullPath: '/nusqa/'
      preLoaderRoute: typeof NusqaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework/': {
      id: '/homework/'
      path: '/homework'
      fullPath: '/homework/'
      preLoaderRoute: typeof HomeworkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId': {
      id: '/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof TestsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/teacher/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/lessons': {
      id: '/teacher/lessons'
      path: '/teacher/lessons'
      fullPath: '/teacher/lessons'
      preLoaderRoute: typeof TeacherLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/homework': {
      id: '/teacher/homework'
      path: '/teacher/homework'
      fullPath: '/teacher/homework'
      preLoaderRoute: typeof TeacherHomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectSlug': {
      id: '/subjects/$subjectSlug'
      path: '/subjects/$subjectSlug'
      fullPath: '/subjects/$subjectSlug'
      preLoaderRoute: typeof SubjectsSubjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework/$hwId': {
      id: '/homework/$hwId'
      path: '/homework/$hwId'
      fullPath: '/homework/$hwId'
      preLoaderRoute: typeof HomeworkHwIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId/result': {
      id: '/tests/$testId/result'
      path: '/result'
      fullPath: '/tests/$testId/result'
      preLoaderRoute: typeof TestsTestIdResultRouteImport
      parentRoute: typeof TestsTestIdRoute
    }
    '/subjects/$subjectSlug/lesson/$lessonId': {
      id: '/subjects/$subjectSlug/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/subjects/$subjectSlug/lesson/$lessonId'
      preLoaderRoute: typeof SubjectsSubjectSlugLessonLessonIdRouteImport
      parentRoute: typeof SubjectsSubjectSlugRoute
    }
  }
}

interface SubjectsSubjectSlugRouteChildren {
  SubjectsSubjectSlugLessonLessonIdRoute: typeof SubjectsSubjectSlugLessonLessonIdRoute
}

const SubjectsSubjectSlugRouteChildren: SubjectsSubjectSlugRouteChildren = {
  SubjectsSubjectSlugLessonLessonIdRoute:
    SubjectsSubjectSlugLessonLessonIdRoute,
}

const SubjectsSubjectSlugRouteWithChildren =
  SubjectsSubjectSlugRoute._addFileChildren(SubjectsSubjectSlugRouteChildren)

interface TestsTestIdRouteChildren {
  TestsTestIdResultRoute: typeof TestsTestIdResultRoute
}

const TestsTestIdRouteChildren: TestsTestIdRouteChildren = {
  TestsTestIdResultRoute: TestsTestIdResultRoute,
}

const TestsTestIdRouteWithChildren = TestsTestIdRoute._addFileChildren(
  TestsTestIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  HomeworkHwIdRoute: HomeworkHwIdRoute,
  SubjectsSubjectSlugRoute: SubjectsSubjectSlugRouteWithChildren,
  TeacherHomeworkRoute: TeacherHomeworkRoute,
  TeacherLessonsRoute: TeacherLessonsRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TestsTestIdRoute: TestsTestIdRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  HomeworkIndexRoute: HomeworkIndexRoute,
  NusqaIndexRoute: NusqaIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
